-- =============================================================
-- LocaCheck V43 — Painel admin, visitas e consultas unificadas
-- Migração aditiva e compatível com a versão anterior.
--
-- ONDE RODAR:
-- Supabase > SQL Editor > New query > cole todo este arquivo > Run.
--
-- IMPORTANTE:
-- 1. Não altera PushinPay.
-- 2. Não altera o bucket records.
-- 3. Não cria trigger em auth.users.
-- 4. Não remove funções ou dados existentes.
-- =============================================================

create extension if not exists pgcrypto;

-- Garante a função de verificação administrativa usada pelas políticas/RPC.
create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and lower(coalesce(role, '')) = 'admin'
  );
$$;

-- -------------------------------------------------------------
-- 1) Visitas do site
-- Cada sessão do navegador é contabilizada no máximo uma vez por dia.
-- Não armazenamos IP, CPF ou dados sensíveis de navegação.
-- -------------------------------------------------------------
create table if not exists public.site_visits (
  id bigint generated by default as identity primary key,
  session_key text not null,
  visit_date date not null,
  path text not null default '/',
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  constraint site_visits_session_key_length check (char_length(session_key) between 16 and 100),
  constraint site_visits_path_length check (char_length(path) between 1 and 250),
  constraint site_visits_session_day_unique unique (session_key, visit_date)
);

create index if not exists site_visits_visit_date_idx
on public.site_visits (visit_date desc);

create index if not exists site_visits_created_at_idx
on public.site_visits (created_at desc);

create index if not exists site_visits_user_id_idx
on public.site_visits (user_id)
where user_id is not null;

alter table public.site_visits enable row level security;

-- Somente administradores podem visualizar pelo cliente.
-- A gravação é feita pela rota segura da Vercel usando service_role.
drop policy if exists "Admins can view site visits" on public.site_visits;
create policy "Admins can view site visits"
on public.site_visits
for select
to authenticated
using (public.is_admin());

revoke insert, update, delete on public.site_visits from anon, authenticated;
grant select on public.site_visits to authenticated;

comment on table public.site_visits is
'Contabiliza uma visita por sessão do navegador por dia, sem armazenar IP ou CPF.';

-- -------------------------------------------------------------
-- 2) Complementos do histórico interno
-- Mantém compatibilidade com os registros antigos.
-- -------------------------------------------------------------
alter table public.consultation_logs
  add column if not exists consultation_type text not null default 'internal';

alter table public.consultation_logs
  add column if not exists included_with_external boolean not null default false;

alter table public.consultation_logs
  add column if not exists external_log_id uuid;

create index if not exists consultation_logs_created_at_idx
on public.consultation_logs (created_at desc);

create index if not exists consultation_logs_user_created_idx
on public.consultation_logs (user_id, created_at desc);

create index if not exists consultation_logs_type_created_idx
on public.consultation_logs (consultation_type, created_at desc);

comment on column public.consultation_logs.included_with_external is
'Indica que a busca interna foi incluída na Consulta Externa Completa, sem cobrança adicional.';

-- -------------------------------------------------------------
-- 3) Resumo seguro para o painel administrativo
-- Une visitas, consultas internas e consultas externas.
-- CPF é devolvido apenas de forma mascarada/final.
-- -------------------------------------------------------------
create or replace function public.get_admin_activity_overview(p_days integer default 7)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_days integer := greatest(1, least(coalesce(p_days, 7), 90));
  v_today date := (now() at time zone 'America/Fortaleza')::date;
  v_start_date date;
  v_start_at timestamptz;
  v_today_at timestamptz;
  v_week_at timestamptz;
  v_result jsonb;
begin
  if auth.uid() is null or not public.is_admin() then
    raise exception 'Acesso permitido apenas para administradores.';
  end if;

  v_start_date := v_today - (v_days - 1);
  v_start_at := (v_start_date::timestamp at time zone 'America/Fortaleza');
  v_today_at := (v_today::timestamp at time zone 'America/Fortaleza');
  v_week_at := ((v_today - 6)::timestamp at time zone 'America/Fortaleza');

  with
  internal_period as (
    select
      l.id::text as id,
      l.user_id,
      p.nome as user_name,
      p.email as user_email,
      case
        when coalesce(l.included_with_external, false) then 'internal_included'
        else coalesce(nullif(l.consultation_type, ''), 'internal')
      end as consultation_type,
      'internal'::text as source,
      case
        when length(regexp_replace(coalesce(l.searched_cpf, ''), '\D', '', 'g')) >= 4
          then 'CPF final ' || right(regexp_replace(l.searched_cpf, '\D', '', 'g'), 4)
        when length(regexp_replace(coalesce(l.searched_text, ''), '\D', '', 'g')) = 11
          then 'CPF final ' || right(regexp_replace(l.searched_text, '\D', '', 'g'), 4)
        else left(coalesce(nullif(trim(l.searched_text), ''), 'Não informado'), 120)
      end as searched_display,
      coalesce(l.results_count, 0)::integer as results_count,
      case when coalesce(l.credit_charged, false) then 1 else 0 end::integer as credits_charged,
      coalesce(l.included_with_external, false) as included_with_external,
      false as cache_hit,
      'success'::text as status,
      l.created_at
    from public.consultation_logs l
    left join public.profiles p on p.id = l.user_id
    where l.created_at >= v_start_at
  ),
  external_period as (
    select
      e.id::text as id,
      e.user_id,
      p.nome as user_name,
      p.email as user_email,
      coalesce(nullif(e.consultation_type, ''), 'external_advanced') as consultation_type,
      'external'::text as source,
      case when nullif(e.cpf4, '') is not null then 'CPF final ' || e.cpf4 else 'CPF não informado' end as searched_display,
      case
        when jsonb_typeof(e.result_summary) = 'object' and e.status = 'success' then 1
        else 0
      end::integer as results_count,
      coalesce(e.credits_charged, 0)::integer as credits_charged,
      false as included_with_external,
      coalesce(e.cache_hit, false) as cache_hit,
      coalesce(nullif(e.status, ''), 'success') as status,
      e.created_at
    from public.external_consultation_logs e
    left join public.profiles p on p.id = e.user_id
    where e.created_at >= v_start_at
  ),
  all_consultations as (
    select * from internal_period
    union all
    select * from external_period
  ),
  daily_visits as (
    select
      day::date as day,
      coalesce(count(v.id), 0)::integer as visits
    from generate_series(v_start_date, v_today, interval '1 day') day
    left join public.site_visits v on v.visit_date = day::date
    group by day::date
    order by day::date
  )
  select jsonb_build_object(
    'period_days', v_days,
    'period_start', v_start_date,
    'period_end', v_today,
    'summary', jsonb_build_object(
      'visits_today', (select count(*) from public.site_visits where visit_date = v_today),
      'visits_7_days', (select count(*) from public.site_visits where visit_date >= v_today - 6 and visit_date <= v_today),
      'visits_period', (select count(*) from public.site_visits where visit_date >= v_start_date and visit_date <= v_today),
      'consultations_today', (
        (select count(*) from public.consultation_logs where created_at >= v_today_at)
        +
        (select count(*) from public.external_consultation_logs where created_at >= v_today_at)
      ),
      'consultations_7_days', (
        (select count(*) from public.consultation_logs where created_at >= v_week_at)
        +
        (select count(*) from public.external_consultation_logs where created_at >= v_week_at)
      ),
      'consultations_period', (select count(*) from all_consultations),
      'internal_period', (select count(*) from all_consultations where source = 'internal'),
      'external_period', (select count(*) from all_consultations where source = 'external'),
      'active_users_period', (select count(distinct user_id) from all_consultations where user_id is not null),
      'credits_period', (select coalesce(sum(credits_charged), 0) from all_consultations)
    ),
    'daily_visits', coalesce((
      select jsonb_agg(jsonb_build_object('date', day, 'visits', visits) order by day)
      from daily_visits
    ), '[]'::jsonb),
    'consultations', coalesce((
      select jsonb_agg(to_jsonb(c) order by c.created_at desc)
      from (
        select *
        from all_consultations
        order by created_at desc
        limit 400
      ) c
    ), '[]'::jsonb)
  ) into v_result;

  return v_result;
end;
$$;

revoke all on function public.get_admin_activity_overview(integer) from public;
grant execute on function public.get_admin_activity_overview(integer) to authenticated;

notify pgrst, 'reload schema';
